# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: CI geeup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      continue-on-error: true
      run: |
        if runner.os =='Windows'
          python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install google-auth==1.27.1
          pip install flake8 pytest pipwin pandas wheel
          pip install poetry
          pipwin refresh
        if runner.os !='Windows'
          python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install google-auth==1.27.1
          pip install flake8 pytest pandas wheel
          pip install poetry
    - name: Test package
      run: |
        python setup.py install
        geeup -h
        geeup init
